### ISSUE TITLE
Create an RMarkdown document showing hyper-parameter estimation

### ISSUE THREAD

**Issue by cboettig** [boettiger-lab/shea#5]
Familiarize yourself with the [rmarkdown format](http://rmarkdown.rstudio.com), and in particular the markdown output format in RStudio. Use this to write a report document (in this GitHub repo) that shows what happens when you simulate data from a GP with known hyper-parameters and then seek to estimate the hyper-parameters using your optim function.  Repeat this process simulating an increasing number of points and see if it improves your estimate.  

Try out the `ggplot2` package as well for making your plots.

**Comment by sheaconlon** [comment]
@cb74d75
https://github.com/boettiger-lab/shea/tree/master/inst/test_optimality
