### ISSUE TITLE
Stochastic Dynamic Programming Primer

### ISSUE THREAD

**Issue by cboettig** [boettiger-lab/shea#6]
Read [this paper](http://doi.org/10.1111/2041-210X.12082) and take a whirl at implementing (or at least running through) the R code needed to solve the Wolf population control problem they illustrate in the paper.  

They provide R code in the supplement that illustrates the algorithm itself, but in general this is more robustly illustrated using the R package, `mdptools`, by the same authors.  Their appendix doesn't actually show solving the problem using `mdptools` functions directly, so add an example that solves the problem by calling `mdptools` functions as well.

**Comment by sheaconlon** [comment]
[Wolf culling optimal control example.pdf](https://github.com/boettiger-lab/shea/files/19720/Wolf.culling.optimal.control.example.pdf)
