### ISSUE TITLE
next steps

### ISSUE THREAD

**Issue by cboettig** [boettiger-lab/shea#7]
## optim_gp

- set sig_noise to 0 and repeat
- show estimated parameters over different sample size
- check convergence flag
- compare likelihood of true parameters to estimates

## sdp

- fix transition matrix for normalization

**Comment by sheaconlon** [comment]
optim_gp https://github.com/boettiger-lab/shea/blob/4aebfcb05346f9c19417677d728ec3e91b1b86ee/inst/notebook/optim_hypers.Rmd
sdp https://github.com/boettiger-lab/shea/blob/4aebfcb05346f9c19417677d728ec3e91b1b86ee/inst/examples/fishery_management.md
