### ISSUE TITLE
GP_optim parameters

### ISSUE THREAD

**Issue by cboettig** [boettiger-lab/shea#8]
@sheaconlon writes:

> Here's the [GP optimization writeup](https://github.com/boettiger-lab/shea/blob/4aebfcb05346f9c19417677d728ec3e91b1b86ee/inst/notebook/optim_hypers.md). When I set the signal variance to zero, it tried to explain all the variability using noise variance. I then tried setting the signal variance to a reasonable nonzero value and that led to a reasonable model, though not the one with the best marginal likelihood unfortunately. optim(...) is returning a 0 exit code and the graph of the hyper parameters versus sample size suggests that a lack of data is not the problem. Do you think there is something wrong with my implementation, the optimization problem is too hard for optim(...), or is this expected?

Very nice job in setting the signal variance to the "teacher's" value -- that make sense to do, but I'd redo that with an exact match (instead of 1.5 vs 2).  It might be cleaner to make both the teacher and the student value 0.  As you observe, it won't help to fix the student at 0 when the teacher isn't at 0, since the student necessarily has to compensate by increasing the process error.  

One big thing we should change is not to base the estimates on a single simulation at a given sampling effort.  Rather than just simulate, say, the 5 points and estimate the GP on that, we really want to produce lots of replicate simulations of the 5 points.  This means you'll have a distribution of estimated parameter values, and we can look a the mean and variance in each case.

Repeat that as we increase the number of points, and you should see the variance in the estimates decreasing (and the mean getting closer to the true value)  This should be easier to observe than catching this pattern with only a single simulation at each sample size.  Make sense?

Remember that a good sanity check on optim is that it should always be returning a likelihood that is as good as or a bit better than the likelihood when you just use the teacher's parameters.  If you can "guess" (i.e. 'cheat' and use the known teacher's parameters) parameter values that's better (smaller negative log likelihood) than optim's estimate, clearly optim isn't doing it's job.   

Lastly, we should consider just how we increase the data scale.  We expect convergence in parameter estimates to scale roughly with the square root of data size, so it might make more sense to increase the data set size as something like `(1:10)^2` or `seq(1,20,by=2)^2`, say.

**Comment by sheaconlon** [comment]
https://github.com/boettiger-lab/shea/blob/6a08a045ed832532e953b5b4067662340bb80d67/inst/notebook/optim_hypers2/optim_hypers2.md
